source 'https://rubygems.org'

gem 'rails', '4.0.0'

gem 'bootstrap-sass-rails'
gem 'cancan'
gem 'capistrano', group: :development
gem 'carrierwave'
gem 'coffee-rails',         '~> 4.0.0'
gem 'country_select'
gem 'devise'
gem 'devise-i18n-views',    '~> 0.2'
gem 'friendly_id',          '~> 5.0.0'
gem 'jquery-rails'
gem 'paper_trail',          '>= 3.0.0.rc2'
gem 'pg'
gem 'rmagick',              '~> 2.13.2'
gem 'sass-rails',           '~> 4.0.0'
gem 'simple_form',          '~> 3.0.1'
gem 'slim'
gem 'uglifier',             '>= 1.3.0'
gem 'unicorn'
gem 'validates_timeliness', '~> 3.0'
