source 'https://rubygems.org'

gem 'rails', '4.0.0'

gem 'bootstrap-sass'
gem 'cancan'
gem 'capistrano',           '~> 2.15'
gem 'carrierwave'
gem 'chartkick'
gem 'cocoon'
gem 'coffee-rails',         '~> 4.0.0'
gem 'country_select'
gem 'coveralls',            require: false
gem 'database_cleaner'
gem 'devise'
gem 'devise-i18n-views',    '~> 0.2'
gem 'differ'
gem 'factory_girl_rails'
gem 'forgery'
gem 'friendly_id',          '~> 5.0.0'
gem 'impressionist',        '~> 1.5.1'
gem 'jquery-rails'
gem 'meta-tags',            require: 'meta_tags'
gem 'mysql2'
gem 'paper_trail',          '>= 3.0.0.rc2'
gem 'rmagick',              '~> 2.13.2'
gem 'rubyzip',              require: 'zip/zip'
gem 'sass-rails',           '~> 4.0.0'
gem 'searchkick'
gem 'sentencify',           '0.4.0'
gem 'simple_form',          '~> 3.0.1'
gem 'slim'
gem 'state_machine',        '1.2.0'
gem 'tabulous'
gem 'therubyracer'
gem 'uglifier',             '>= 1.3.0'
gem 'unicorn'
gem 'validates_timeliness', '~> 3.0'
gem 'will_paginate-bootstrap'
gem 'zip-zip'

group :development, :test do
  gem 'rspec-rails',        '~> 3.0.0.beta'
  gem 'shoulda-matchers'
end
