source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.0.0'

gem 'bootstrap-sass-rails'
gem 'cancan'
gem 'capistrano',           group: :development
gem 'carrierwave'
gem 'cocoon'
gem 'coffee-rails',         '~> 4.0.0'
gem 'country_select'
gem 'devise'
gem 'devise-i18n-views',    '~> 0.2'
gem 'friendly_id',          '~> 5.0.0'
gem 'jquery-rails'
gem 'mysql2'
gem 'paper_trail',          '>= 3.0.0.rc2'
gem 'rmagick',              '~> 2.13.2'
gem 'sass-rails',           '~> 4.0.0'
gem 'searchkick'
gem 'sentencify',           '0.4.0'
gem 'simple_form',          '~> 3.0.1'
gem 'slim'
gem 'state_machine',        '1.2.0'
gem 'tabulous'
gem 'uglifier',             '>= 1.3.0'
gem 'unicorn'
gem 'validates_timeliness', '~> 3.0'
gem 'will_paginate-bootstrap'

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
